### PR TITLE
Generate unique address

### LINKED ISSUE #4: Allow requesting unique values
See the original PR: https://github.com/stympy/faker/pull/752

### PR DESCRIPTION
**Pull request by rickychilcott**
This is a WIP branch that generates unique values similar to how the ruby gem provides unique values.

I'm not sure I like this approach but it's the only thing I could come up with.

The API will expand to provide `unique_*` methods. (e.g. `Faker::Address.city` and `Faker::Address.unique_city`)

I use a crystal macro to generate both versions. Can you give this a review @askn and see if you like this approach? If not, can you share an alternative approach that might be better and I can investigate or submit another PR?

When complete, this will fix #4

### CODE REVIEW

**Comment by rickychilcott** [comment]
Also, to clarify, this is only done for one method at the moment. I'll expand it to work with all classes and modularize when the approach is settled.

**Comment by askn** [comment]
Thanks for your contribution 🎉Looks nice. I can't find a different solution, it is ok for me 👍

**Comment by rickychilcott** [comment]
Ok. Thanks. I'm making progress on this, but I have to determine how to build a macro that will allow an arbitrary number of arguments to be passed through it.

I now have each of the builders inherit from `Faker::Base` (https://github.com/askn/faker/pull/7/files#diff-80675a4903ffbf06d19c5f72efa31dd3) so we can easily add more functionality there

**Comment by watzon** [comment]
This would be really nice to get merged in if it's working

**Comment by rickychilcott** [comment]
Super funny, I was thinking about Crystal earlier today (before this request was made). Let me see if I can work in trying to make this work for all/most of the methods and go from there.

I'm not sure I actually think this is really the most idiomatic way to do this with a typed language, but it's worth it to have the feature working for people at this time.

**Comment by rickychilcott** [comment]
I worked on this a bit last night and have something that kinda works. Can I get a review @askn?

I think I've got an issue where my macro doesn't actually pass in the arguments to the non-uniqued version. Do you know macros well enough to determine how to do this properly?

**Comment by rickychilcott** [comment]
@askn Do you have time to review and merge or provide feedback?

**Pull request merged**
